version: '3.8'

services:
  node-app:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FINNHUB_API_KEY=cp1pfm1r01qhquusc7kgcp1pfm1r01qhquusc7l0
      - ALPHA_VANTAGE_API_KEY=0AULH1IPAU7XSK69
      - MONGO_DB_URI=mongodb://mongo:27017/market-overview?retryWrites=true&w=majority
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
