version: '3.8'

services:
  node-app:
    build:
      context: ./
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=3001
      - FINNHUB_API_KEY=cp1pfm1r01qhquusc7kgcp1pfm1r01qhquusc7l0
      - ALPHA_VANTAGE_API_KEY=0AULH1IPAU7XSK69
      - MONGO_DB_URI=mongodb://mongo:27017/market-overview?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
